import { type NextPage } from "next";
import Head from "next/head";
import WalletConnection from "~/components/WalletConnection";
import WalletInfo from "~/components/WalletInfo";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>inkathon dApp</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#1b1e32] to-[#3b949f]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            ink<span className="text-[#4f94da] text-opacity-50">!</span>athon
            dApp
          </h1>
          <WalletConnection></WalletConnection>
          <WalletInfo></WalletInfo>
        </div>
      </main>
    </>
  );
};

export default Home;
